# Generated by Django 4.0.4 on 2022-04-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
